title: Ocean 
author: Ocean
email: oceanwong524@gmail.com
description: awesome steak
# social links
twitter_username: oceanwong524 # DO NOT include the @ character, or else the build will fail!
github_username:  WongNgouShan # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
